name: .NET

on:
  push:
    tags: [ "release/*" ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # Publish framework dependant
    - name: Publish linux-x64
      run: dotnet publish --configuration Release --output ./publish/L64 --runtime linux-x64  --self-contained false -p:PublishSingleFile=true -nologo
    
    - name: Publish linux-arm
      run: dotnet publish --configuration Release --output ./publish/Larm --runtime linux-arm  --self-contained false -p:PublishSingleFile=true -nologo

    - name: Publish linux-arm64
      run: dotnet publish --configuration Release --output ./publish/Larm64 --runtime linux-arm64  --self-contained false -p:PublishSingleFile=true -nologo

    - name: Publish osx-x64
      run: dotnet publish --configuration Release --output ./publish/osx --runtime osx-x64  --self-contained false -p:PublishSingleFile=true -nologo

    - name: Publish win-x64
      run: dotnet publish --configuration Release --output ./publish/W64 --runtime win-x64  --self-contained false -p:PublishSingleFile=true -nologo

    # Publish fully contained
    - name: Publish linux-x64
      run: dotnet publish --configuration Release --output ./publish/L64-contained --runtime linux-x64  --self-contained true -p:PublishTrimmed=true  -p:PublishSingleFile=true -nologo
    
    - name: Publish linux-arm
      run: dotnet publish --configuration Release --output ./publish/Larm-contained --runtime linux-arm  --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -nologo

    - name: Publish linux-arm64
      run: dotnet publish --configuration Release --output ./publish/Larm64-contained --runtime linux-arm64  --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -nologo

    - name: Publish osx-x64
      run: dotnet publish --configuration Release --output ./publish/osx-contained --runtime osx-x64  --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -nologo

    - name: Publish win-x64
      run: dotnet publish --configuration Release --output ./publish/W64-contained --runtime win-x64  --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -nologo

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./publush/L64/rnd
          ./publush/Larm/rnd
          ./publush/Larm64/rnd
          ./publush/L64-contained/rnd
          ./publush/Larm-contained/rnd
          ./publush/Larm64-contained/rnd
          ./publush/osx/rnd
          ./publush/osx-contained/rnd
          ./publush/win64/rnd.exe
          ./publush/win64-contained/rnd.exe
          
