name: .NET

on:
  push:
    branches: [ release/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    # Un-contained
    - name: Publish normal linux-64
      run: dotnet publish -nologo -c release --self-contained false --runtime linux-x64
    - name: Publish normal linux-arm
      run: dotnet publish -nologo -c release --self-contained false --runtime linux-arm
    - name: Publish normal osx-x64
      run: dotnet publish -nologo -c release --self-contained false --runtime osx-x64
    - name: Publish normal win-x64
      run: dotnet publish -nologo -c release --self-contained false --runtime win-x64
    # Contained
    - name: Publish Contained linux-64
      run: dotnet publish -nologo -c release --self-contained true --runtime linux-x64
    - name: Publish Contained linux-arm
      run: dotnet publish -nologo -c release --self-contained true --runtime linux-arm
    - name: Publish Contained osx-x64
      run: dotnet publish -nologo -c release --self-contained true --runtime osx-x64
    - name: Publish Contained win-x64
      run: dotnet publish -nologo -c release --self-contained true --runtime win-x64
